### ISSUE TITLE
[TwigComponent] Using `<twig:Component attr="">` syntax throw a syntax error

### ISSUE THREAD

**Issue by Kocal** [symfony/ux#1002] opened 2023-07-11 08:28 UTC
Hi everyone 👋🏻 

We've created an `Image` component that allows us to render a `<img>` with some default attributes (`loading`, `decoding`, ...), but we faced when trying to render an empty `alt` (which is pretty common for decorative image):

The following code `<twig:Image src="./img.png" alt="" />` throw an error due to the empty `alt` property: 
<img width="958" alt="image" src="https://github.com/symfony/ux/assets/2103975/2b1509e4-2785-48fc-89d5-ce7f63393940">

The problem occurs with `symfony/ux-twig-component` 2.9.1 and 2.10.0. 

I can try to work on a PR tonight.

Thanks!

**Comment by weaverryan** [comment] 2023-07-11 16:35
Hey @Kocal!

This is a duplicate of #925. But the important point is: yes, this needs a fix and you're not the first person to hit the problem :).

**Closed as completed by weaverryan** 2023-07-11 16:35 UTC

**Comment by Kocal** [comment] 2023-07-11 17:03
Oh, my bad, thanks!
