### ISSUE TITLE
[TwigComponent] Twig linter does not recognize anonymous components

### ISSUE THREAD

**Issue by ker0x** [symfony/ux#1089] opened 2023-09-01 18:18 UTC
When I run the following command

```bash
bin/console lint:twig templates/ --format=github
```

I got this message

```bash
Unknown component "common:atoms:badge:default". And no matching anonymous component template was found.
```

**Comment by weaverryan** [comment] 2023-09-01 23:45
Ooooh, how odd. WDYT @WebMamba?

**Comment by WebMamba** [comment] 2023-09-02 10:29
This looks expected since this commit: https://github.com/symfony/ux/pull/1031/commits/eeef2043ddadad0ee9b38f95dd4bd1b637963542.
@ker0x do a quick check in your templates, to see if you have somewhere `<twig:common:atoms:badge:default/>`, if not please provide a reproducer, everything works as expected on my side.

**Comment by aszenz** [comment] 2023-10-03 21:48
Faced the same issue after trying anonymous components. 

Using the debugger i found that that ComponentTemplateFinder classes environment was using `ArrayLoader` and only contained the template where the anonymous component was used `templates/ComponentShowcase/buttons/index.html.twig` and not the actual component file `templates/Component/Button.html.twig`.

https://github.com/symfony/ux/blob/b47c679cd30cfb6dc7f1f1e784434281f1f80d47/src/TwigComponent/src/ComponentTemplateFinder.php#L22

Causing this check to return false since the component file `components/Button.html.twig` wasn't found in the loader:

https://github.com/symfony/ux/blob/b47c679cd30cfb6dc7f1f1e784434281f1f80d47/src/TwigComponent/src/ComponentTemplateFinder.php#L57-L58


Note: I was using `<twig:Button>` inside a twig macro defined in `templates/ComponentShowcase/buttons/index.html.twig`

**Comment by smnandre** [comment] 2023-10-09 22:44
Hello @aszenz !

I cannot reproduce your problem, could you provide a minimal reproducer ? 

What version of symfony/ux-twig-component are you using ?

**Comment by ebitkov** [comment] 2023-10-10 08:09
Having the same error. Made a quick symfony repo to reproduce it:
https://github.com/ebitkov/symfony-ux-twig-component-lint-error

Running `symfony console lint:twig` throws an exception in ComponentFactory line 244.

Interestingly, if you leave the component empty (`<twig:button/>`) no error is thrown.

**Comment by smnandre** [comment] 2023-10-12 12:44
Well i tried with your reproducer and 

* there is a small typo, the template should be button.html.twig (you forgot the ".html" part) (this has no incidence on our matter)
* the component works and is displayed (2.12 or 2.x-dev with config)
* there is indeed a problem with the linter and i'm not sure why

If it's "only" a lint config problem i'm not too worried, but it's something we'll have to keep an eye on (and fix)..

If you cannot use the component it's something else i agree

**Comment by ebitkov** [comment] 2023-10-12 12:55
@smnandre yes, the component works fine. So far the error only occurs when linting the templates (not sure, if @ker0x and @aszenz refer to the same bug, tho).

But it breaks my CI, which checks the templates before pushing to production. It's not "system breaking", but still annoying.

edit: the ".html" part is as far as I know a "best-practice" thing and shouldn't break anything. Because of that I actually didn't noticed the "typo", since it worked fine without :)

**Comment by smnandre** [comment] 2023-10-12 13:17
> But it breaks my CI, which checks the templates before pushing to production. It's not "system breaking", but still annoying.

I totally agree and i'd love to take a look when i have time.. In the meantime,if you have some time too, feel free to start one and i'll join you (or anyone here with a bit of time) ! 

>  the ".html" part is as far as I know a "best-practice" thing and shouldn't break anything. Because of that I actually didn't noticed the "typo", since it worked fine without :)

Just to give you a heads-up, in 2.13, with the new anonymous mapping system (optional, but will be the main system in 3.0), only the ".html.twig" will be mapped

**Comment by ker0x** [comment] 2023-10-12 14:35
> @smnandre yes, the component works fine. So far the error only occurs when linting the templates (not sure, if @ker0x and @aszenz refer to the same bug, tho).

Same here, components are working fine. It's just on linting them that I get errors.

**Comment by smnandre** [comment] 2023-10-12 17:11
Could you test with next TwigComponent version ? (2.x-dev)

**Comment by smnandre** [comment] 2023-10-12 23:13
Thank you @ker0x  @aszenz & @ebitkov . All your messages helped me understand the problem(s).

There are  in fact two different problems we need to address.

1/ Internal difference between function and tag

We do not check the component name during the compilation when called in `{{ component('FooBarBaz') }}` function, but we do when called in tag `{% component 'FooBarBaz' %}`

Self-closing "HTML" component are transformed into function call during prelex ... that's why you can type <twig:WhateverYouWant /> and it will always seem valid to the lint command.

On the contrary, every "tag" component is validated, so the componentFactory is called, allowing us to check the existence of the component. BUT...

2/ Runtime TemplateComponentFinder instanciation

During the lint, there is indeed a switch of Loader... 

```php
$realLoader = $this->twig->getLoader();
        try {
            $temporaryLoader = new ArrayLoader([$file => $template]);
            $this->twig->setLoader($temporaryLoader);
            $nodeTree = $this->twig->parse($this->twig->tokenize(new Source($template, $file)));
            $this->twig->compile($nodeTree);
            $this->twig->setLoader($realLoader);
```
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bridge/Twig/Command/LintCommand.php

So as the `TemplateComponentFinder` has not be instanciated before, when it call environment::getLoader(), the loader it uses then to check if a template exists... is the empty one set in the command.... which does not know the template. 

We have a couple of options there, but i'd like to remove the Environment dependency, and replace it with a LoaderInterface (the `twig.loader` service), removing this kind of runtime-effect.

WDYT ?

**Comment by weaverryan** [comment] 2023-10-13 13:03
That's some excellent deep diving :).

> We have a couple of options there, but i'd like to remove the Environment dependency, and replace it with a LoaderInterface (the twig.loader service), removing this kind of runtime-effect.

What do you propose exactly?

**Comment by WebMamba** [comment] 2023-10-13 15:32
Do you know the reason why we have a different loader  ?

**Comment by smnandre** [comment] 2023-10-13 17:20
We dont :) the code i showed come from the lint command, which swap the real loader with a minimal one for each template. And as the component template finder is not instanciated before…

**Comment by smnandre** [comment] 2023-10-13 17:22
> That's some excellent deep diving :).
> 
> > We have a couple of options there, but i'd like to remove the Environment dependency, and replace it with a LoaderInterface (the twig.loader service), removing this kind of runtime-effect.
> 
> What do you propose exactly?

Replace Environment with LoaderInterface in the constructor, inject « twig.loader » instead of « twig » (and maybe « template.iterator », one stone two birds…. )

**Comment by weaverryan** [comment] 2023-10-16 17:44
> Replace Environment with LoaderInterface in the constructor, inject « twig.loader » instead of « twig » (and maybe « template.iterator », one stone two birds…. )

You're referring to https://github.com/symfony/ux/blob/2.x/src/TwigComponent/src/ComponentRenderer.php right? And can you clarify what you mean by the template iterator? Or you can make a PR - you've clearly dove deep into this, which I appreciate.

**Closed as completed** 2023-10-18 14:32 UTC
Labels: Bug
