### ISSUE TITLE
Lazily loaded controllers

### ISSUE THREAD

**Issue by zmitic** [symfony/ux#14] opened 2020-12-05 13:49 UTC
Is it possible to support them with this package: https://github.com/danieldiekmeier/stimulus-controller-resolver ?

Wouldn't 

```js
    "controllers": {
        "@symfony/ux-chartjs": {
            "chart": {
                "enabled": true,
                "webpackMode": "eager"
            }
        }
    },
```

load all of them; is that correct?

**Comment by stof** [comment] 2020-12-05 15:04
with `webpackMode: eager`, loading them early is expected. The issue is that even the lazy mode does not actually lazy-load things. that's already reported on https://github.com/symfony/stimulus-bridge/issues/3 which is the package responsible for that (symfony/ux is about the core UX packages being provided, not the underlying tooling).
So I'm closing that one as a duplicate of https://github.com/symfony/stimulus-bridge/issues/3

**Closed by stof** 2020-12-05 15:04 UTC
