### ISSUE TITLE
[LiveComponent] Issues with custom Stimulus controller

### ISSUE THREAD

**Issue by althaus** [symfony/ux#612] opened 2022-12-15 12:55 UTC
Hey,

I'm currently trying to integrated some legacy JS (e.g. DatePicker, MarkdownEditor, Autocomplete) into a Live Component based form.

I went with the steps described here:

https://symfony.com/bundles/ux-live-component/current/index.html#working-with-the-component-in-javascript

I'm using `symfony/ux-twig-component@2.x-dev` as `attributes.add`  hasn't been released yet.

I've build a simple Stimulus controller:

~~~js
import { Controller } from '@hotwired/stimulus';

export default class extends Controller {
    connect() {
        console.log('connect', this.element);

        this.element.addEventListener('live:connect', (event) => {
            this.component = event.detail.component;
            console.log('live:connect', this.component);

            this.component.on('render:finished', (component) => {
                console.log('render:finished', this.element, component);
            });
        });
    }
}
~~~

This one works on the latest 2.6.1 release when I attach on an element **around** the Live Component, but that approach results into an element inception and the listeners gets attached again on each render pass.

On 2.x-dev the controller is properly attached to the component and the event listener is registered... but it's not triggered anymore.

![grafik](https://user-images.githubusercontent.com/105975/207863892-bf34f595-a56a-4276-b367-a20ec6b6fe82.png)

![grafik](https://user-images.githubusercontent.com/105975/207863952-25d1bd6b-0f42-42bf-8eeb-4381dc31b5ba.png)

![grafik](https://user-images.githubusercontent.com/105975/207864096-c7dae117-60ca-4550-9c80-4a5ade4bfd1f.png)

Has something different changed? Do I miss something?

Cheers
Matthias

PS: I really like the Live thingy. <3

**Comment by weaverryan** [comment] 2022-12-15 13:40
Hi!

Hmm. First, I know this wasn’t the point of your issue, but could you explain this problem further? 

> This one works on the latest 2.6.1 release when I attach on an element around the Live Component, but that approach results into an element inception and the listeners gets attached again on each render pass.


About the actual issue, my guess is that the problem isn’t how the live:connect is dispatched (I don’t think anything in this area has changed), but that something is different when you attach to the root component element vs attaching to a parent. Here’s what’s going on: your editForm controller is “connecting” right *after* the live controller. And so, by the time you attach your listener for live:connect, that event has already happened! This was actually mentioned by another user on Slack a few days ago and it’s something we definitely need to address (so thanks for opening the issue).

What’s the solution? I can think of 2 possibilities so far:

A) make sure that “live” appears last in the data-controller attribute. We could make that happen, but it feels delicate. 

B) experiment with adding a 1ms or 10ms setTimeout() before we dispatch the event. That should, in theory, allow any other controllers to be connected.

C) some other solution for getting the Component object from the root controller element??? You can use this.element.__controller… but only if the live controller is connected already. So, it would work only in the exact opposite situations as live:connect 🙃. Perhaps there could be some new ComponentRegistry where you can fetch components? Like:

```
import { ComponentRegistry } from “@symfony/ux-live-component”;

// …

const component = await ComponentRegistry.get(this.element);
```

**Comment by 1ed** [comment] 2022-12-16 01:28
> This was actually mentioned by another user on Slack a few days ago and it’s something we definitely need to address (so thanks for opening the issue).

Hi, it was me, and I haven't had time to open an issue yet, sorry. But I'll just write my findings here then.

I think this is kind of 2 different problems. We can not add a controller before another one using `attributes`, I opened #613 for that, but maybe that is not the way to go, feel free to close it, and in that case I think we should deprecate and remove `add` too.  

The other problem is that the order of loading (registering) controllers can be different on the first page load and the others. That's coming from `@symfony/stimulus-bridge` and how it registers the controllers, which I don't really understand yet. Rails uses these methods https://github.com/hotwired/stimulus-rails/blob/main/app/assets/javascripts/stimulus-loading.js, but it might have similar problems https://github.com/hotwired/stimulus-rails/issues

**Comment by althaus** [comment] 2022-12-16 13:53
> Hi!
> 
> Hmm. First, I know this wasn’t the point of your issue, but could you explain this problem further?
> 
> > This one works on the latest 2.6.1 release when I attach on an element around the Live Component, but that approach results into an element inception and the listeners gets attached again on each render pass.

My first try was this:

~~~twig
<div id="form-edit" data-controller="editform">
    <div {{ attributes }}>
      {{ form }}
    </div>
</div>
~~~

But then on each reload the outer div got replicated:

~~~twig
<div id="form-edit" data-controller="editform">
    <div id="form-edit" data-controller="editform">
        <div {{ attributes }}>
~~~

And then the event were attached again... so after 5 re-renders I had my div put 5 times into itself and 5 event listeners.
 
> About the actual issue, my guess is that the problem isn’t how the live:connect is dispatched (I don’t think anything in this area has changed), but that something is different when you attach to the root component element vs attaching to a parent. Here’s what’s going on: your editForm controller is “connecting” right _after_ the live controller. And so, by the time you attach your listener for live:connect, that event has already happened! This was actually mentioned by another user on Slack a few days ago and it’s something we definitely need to address (so thanks for opening the issue).
> 
> What’s the solution? I can think of 2 possibilities so far:
> 
> A) make sure that “live” appears last in the data-controller attribute. We could make that happen, but it feels delicate.
> 
> B) experiment with adding a 1ms or 10ms setTimeout() before we dispatch the event. That should, in theory, allow any other controllers to be connected.
> 
> C) some other solution for getting the Component object from the root controller element??? You can use this.element.__controller… but only if the live controller is connected already. So, it would work only in the exact opposite situations as live:connect 🙃. Perhaps there could be some new ComponentRegistry where you can fetch components? Like:
> 
> ```
> import { ComponentRegistry } from “@symfony/ux-live-component”;
> 
> // …
> 
> const component = await ComponentRegistry.get(this.element);
> ```

Not sure about A), but running with delays like B) never feels really clean. A dedicated solution like C) sounds promising. With `await` it'd be guaranteed that things are timed correctly?

btw: Instead of the documented solution:

~~~twig
<div id="editform" {{ attributes.add(stimulus_controller('editform')) }}>
~~~

I've randomly tried to put my controller around again, but without the `id` attribute:

~~~twig
<div data-controller="editform">
    <div id="editform" {{ attributes }}>
~~~

and this somehow seems to work?

![grafik](https://user-images.githubusercontent.com/105975/208113172-7963c0b4-d40a-4221-8dbc-ac5a49684d76.png)

**Comment by weaverryan** [comment] 2022-12-20 02:18
> My first try was this:

```
<div id="form-edit" data-controller="editform">
    <div {{ attributes }}>
      {{ form }}
    </div>
</div>
```

Yea... that's not legal. The `{{ attributes }}` element needs to be your root, outer element. Should that be clarified in the docs (or were you, at this point, just experimenting to see what was possible)?

> With await it'd be guaranteed that things are timed correctly?

Yup! I currently think this is the way to go. I haven't written any code yet, but it seems like will work.

**Comment by weaverryan** [comment] 2022-12-20 03:57
Ok, check out #621 :)

**Comment by norkunas** [comment] 2022-12-21 06:13
`this.element.addEventListener('live:connect')` hook could be replaced with stimulus outlet, no? :)

**Comment by weaverryan** [comment] 2023-01-09 15:47
Outlets - new to Stimulus 3.2 - https://stimulus.hotwired.dev/reference/outlets - I have not looked at these yet. So, indeed, they might be usable in some way.

**Closed as completed** 2023-01-19 15:31 UTC
Labels: Bug
