### ISSUE TITLE
ux-dropzone - Error connecting controller

### ISSUE THREAD

**Issue by dprzygodzki** [symfony/ux#33] opened 2020-12-09 19:41 UTC
I'm doing something wrong. Once implemented ux-dropzone, I'm getting an error in the browser console:

> Error connecting controller
>
> DOMException: Failed to execute 'matches' on 'Element': '[data-@symfony/ux-dropzone/dropzone-target~="input"]' is not a valid > selector.

**Comment by tgalopin** [comment] 2020-12-09 19:47
Hi! Can you paste your usage code here?

**Comment by tgalopin** [comment] 2020-12-09 19:51
By seeing `[data-@symfony/ux-dropzone/dropzone-target~="input"]`, it feels like you're implementing your own HTML, is that the case? If so, can you tell me more about how you use the package?

**Comment by Fredxd** [comment] 2020-12-11 08:40
Hi @tgalopin,
I have same here.

## Front side

* I have move my controllers.js and my bootstrap.js file into shared folder in assets/.
* I have correctly called my boostrap.js in my entry.js file
* In my controllers.js i have add
```
"@symfony/ux-dropzone": {
            "dropzone": {
                "enabled": true,
                "webpackMode": "eager",
                "autoimport": {
                    "@symfony/ux-dropzone/src/style.css": true
                }
            }
        }
```

* In my webpack.config.js i have correctly change my path for enableStimulusBridge

## Back Side
* I have add new property imageFile like this (I use VichUploader: it's maybe that ?)
```
 /**
     * @Vich\UploadableField(mapping="adverts", fileNameProperty="imageName")
     */
    private ?File $imageFile;
```

* In my FormType i have
```
            ->add('imageFile', DropzoneType::class, [
                'label' => 'Image',
                'label_attr' => [
                    'class' => 'text-right',
                ],
            ])
```

I hope this can help you

**Comment by Ncaln** [comment] 2020-12-14 17:13
I am also having the same issue.

Could this be related to stimulus new syntax for target attributes?
> The new format is data-[identifier]-target="[name]" instead of data-target="[identifier].[name]"

**Comment by tgalopin** [comment] 2020-12-14 17:46
It seems to be ... but I'm not sure how to reproduce! If you have a reproducer for me that would be awesome :)

**Comment by Fredxd** [comment] 2020-12-14 17:56
> It seems to be ... but I'm not sure how to reproduce! If you have a reproducer for me that would be awesome :)

@tgalopin Hi,
You can see above what i did in order to have this issue ;)

**Comment by Ncaln** [comment] 2020-12-14 17:56
It does look like the form_theme.html.twig uses the old format. Is that the issue, or should it still function properly?

**Comment by disjfa** [comment] 2020-12-14 20:31
I have setup an example project to use for myself with the same error. Just a simple basic setup with a simple crud. I set it up using the basic make commands and added the ux data in my controller.

https://github.com/disjfa/symfony-ux-demo

Same error as above. if anyone can point out where we go wrong it would be apreciated.

```Error connecting controller

DOMException: Failed to execute 'matches' on 'Element': '[data-@symfony/ux-dropzone/dropzone-target~="input"]' is not a valid selector.
```

**Comment by Ncaln** [comment] 2020-12-14 20:44
I also created a repo. It is probably similar setup as @disjfa but in case it's helpful 
[https://github.com/Ncaln/symfony_ux_dropzone_issue_33](url)

**Comment by Kocal** [comment] 2020-12-14 20:59
I'm not familiar with Stimulus, but since we already define `data-controller="@symfony/ux-dropzone/dropzone"` (https://github.com/symfony/ux/blob/main/src/Dropzone/Resources/views/form_theme.html.twig#L5), should we really use `data-target="@symfony/ux-dropzone/dropzone.input"` instead of `data-target="input"`?

**Comment by Kocal** [comment] 2020-12-14 21:03
I'm not familiar with Stimulus, but if I'm not wrong it seems that targets are defined by using the controller name. 
E.g., if you have `data-controller="search"`, you can define a target with `data-search-target="results"`.
Here, the controller name is [`@symfony/ux-dropzone/dropzone`](https://github.com/symfony/ux/blob/main/src/Dropzone/Resources/views/form_theme.html.twig#L2), so Stimulus will try to find [all targets](https://github.com/symfony/ux/blob/main/src/Dropzone/Resources/assets/src/controller.js#L15) by using `[data-@symfony/ux-dropzone/dropzone-target~="the target name"]` selector, which is an invalid selector.

**Comment by tgalopin** [comment] 2020-12-14 22:13
Thanks, I'll have a look, I may have missed something when I tried to reproduce.

**Comment by tgalopin** [comment] 2020-12-14 22:33
The `@` is fine, the only problem is the slashes with Stimulus 2. I propose to normalize them here: https://github.com/symfony/stimulus-bridge/pull/9

**Comment by Fredxd** [comment] 2020-12-15 21:30
@tgalopin 👋
I see you have close your PR, you have see anything in order to fix this issue?

Thanks for your help 👍

**Comment by Kocal** [comment] 2020-12-16 08:07
Hi, I was able to get Dropzone working by:
- replacing `@symfony/ux-dropzone/dropzone` to `symfony--ux-dropzone--dropzone` in `Resources/views/form_theme.html.twig`
- using @tgalopin's works on https://github.com/symfony/stimulus-bridge/pull/9, but using `controllerName = controllerName.replace(/\//g, '--').replace('^@', '')` (which replace all `/` and the `@` at the begin of the controller name)



![Capture d’écran de 2020-12-16 09-02-39](https://user-images.githubusercontent.com/2103975/102321093-7b7a3300-3f7d-11eb-8608-edab1e27dd9c.png)


Some deprecations warning are displayed, maybe we can fix them too:
![Capture d’écran de 2020-12-16 09-06-35](https://user-images.githubusercontent.com/2103975/102321500-08bd8780-3f7e-11eb-989c-5a9a8adc0f50.png)

@tgalopin I can send a PR this evening if you want.

**Comment by tgalopin** [comment] 2020-12-16 10:58
I started working on it on my side too. See https://github.com/stimulusjs/stimulus/pull/351#issuecomment-745513169

I'll open a PR to fix Dropzone as soon as we have something good on stimulus side.

**Comment by Kocal** [comment] 2020-12-16 11:05
Indeed that would be a better solution!

**Comment by AxelBriche** [comment] 2020-12-18 20:24
Hello, when can we hope a fix online please?

**Comment by tgalopin** [comment] 2020-12-29 17:48
After testing many options, I ended up with this simple solution which feels the best: https://github.com/symfony/stimulus-bridge/pull/12. Once merged, this package should be fixable trivially.

**Closed** 2021-01-07 10:59 UTC
