### ISSUE TITLE
[Live] Bind to an empty select in a child is broken

### ISSUE THREAD

**Issue by 1ed** [symfony/ux#629] opened 2022-12-29 16:41 UTC
Hi, the following test logs on console.error

```ts
    it('handles child with empty select', async () => {
        const test = await createTest({}, (data: any) => `
            <div ${initComponent(data)}>
                <div
                    ${initComponent({ selected: '' }, {}, {id: 'the-child-id'})}
                    data-model="foodName"
                    data-testid="child"
                >
                    <select data-model="selected"></select>
                </div>
            </div>
        `);

        await test.component.render()
        // @todo assert on console.error
        expect(test.element.querySelectorAll('select')).toHaveLength(1)
    });
```

```ts
 console.error
    Error initializing controller
    
    Error: The model name "selected" was never initialized. Did you forget to expose "selected" as a LiveProp? Available models values are: foodName
        at setDeepData (/home/egabor/work/open-source/symfony-ux/src/LiveComponent/assets/src/data_manipulation_utils.ts:71:19)
        at _default.set (/home/egabor/work/open-source/symfony-ux/src/LiveComponent/assets/src/Component/ValueStore.ts:52:21)
        at forEach (/home/egabor/work/open-source/symfony-ux/src/LiveComponent/assets/src/Component/plugins/SetValueOntoModelFieldsPlugin.ts:65:38)
        at Proxy.forEach (<anonymous>)
        at _default.synchronizeValueOfModelFields (/home/egabor/work/open-source/symfony-ux/src/LiveComponent/assets/src/Component/plugins/SetValueOntoModelFieldsPlugin.ts:33:60)
        at _default.attachToComponent (/home/egabor/work/open-source/symfony-ux/src/LiveComponent/assets/src/Component/plugins/SetValueOntoModelFieldsPlugin.ts:15:14)
        at Component.addPlugin (/home/egabor/work/open-source/symfony-ux/src/LiveComponent/assets/src/Component/index.ts:88:16)
        at forEach (/home/egabor/work/open-source/symfony-ux/src/LiveComponent/assets/src/live_controller.ts:96:28)
        at Array.forEach (<anonymous>)
        at extended.initialize (/home/egabor/work/open-source/symfony-ux/src/LiveComponent/assets/src/live_controller.ts:95:17)
        at new Context (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:1080:33)
        at Module.fetchContextForScope (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:1296:27)
        at Module.connectContextForScope (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:1282:34)
        at Router.scopeConnected (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:1599:24)
        at ScopeObserver.elementMatchedValue (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:1519:31)
        at ValueListObserver.tokenMatched (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:810:31)
        at TokenListObserver.tokenMatched (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:743:27)
        at /home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:737:42
        at Array.forEach (<anonymous>)
        at TokenListObserver.tokensMatched (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:737:20)
        at TokenListObserver.elementMatchedAttribute (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:726:18)
        at AttributeObserver.elementMatched (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:504:31)
        at ElementObserver.addElement (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:452:39)
        at ElementObserver.refresh (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:373:26)
        at ElementObserver.start (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:343:22)
        at AttributeObserver.start (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:480:34)
        at TokenListObserver.start (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:708:36)
        at ValueListObserver.start (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:791:36)
        at ScopeObserver.start (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:1497:36)
        at Router.start (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:1567:32)
        at Application.start (/home/egabor/work/open-source/symfony-ux/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:1651:25)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      [stack]: 'Error: The model name "selected" was never initialized. Did you forget to expose "selected" as a LiveProp? Available models values are: foodName\n' +
```

There is a reproducer here: https://github.com/1ed/symfony-ux-demos/commit/9335701306f04b0d75a417a75987ab8b0b19d6e1

Using the child only without the parent context it works.

**Comment by 1ed** [comment] 2022-12-29 18:33
After some debugging I noticed `elementBelongsToThisComponent` returns true because `component.getChildren()` is empty at the time when it runs. When the parent connects for the first time it does not know about its children, so it thinks the child's model belongs to itself.

If we have an input field instead of a select no error happens because [synchronizeValueOfModelFields]( https://github.com/symfony/ux/blob/dc6d8312b8663051957c4096af3d1e082cd0796a/src/LiveComponent/assets/src/Component/plugins/SetValueOntoModelFieldsPlugin.ts#L32) does not care about it, but select fields handled differently by
https://github.com/symfony/ux/blob/dc6d8312b8663051957c4096af3d1e082cd0796a/src/LiveComponent/assets/src/Component/plugins/SetValueOntoModelFieldsPlugin.ts#L62-L66
this code force put a value into the value store even if its not belongs to that component, but its child.

**Comment by weaverryan** [comment] 2023-04-14 14:19
Hi! I just tested this on 2.8, and in practice, the issue is gone.

The underlying issue of "the parent component isn't aware of its child components early enough" is still there. However, in 2.8 (I can't remember exactly when this changed), the parent component will see that it doesn't have a `selected` model and will SKIP trying to set the field (and having an error). Then, a moment later, the child will correctly set it.

So, closing - we can reopen if we find there is still a practical problem.

Thanks!

**Closed as completed by weaverryan** 2023-04-14 14:19 UTC
